### ISSUE TITLE
support terraform init --upgrade

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/bitops#104]
# Description
We had a situation where terraform plan was failing as the underlying terraform provider stopped supporting the `config_output_path` variable in the `terraform-aws-eks` module.

a way to resolve this is: Run `terraform init --upgrade` which should get new terraform providers and update the state files to handle any deprecated variables.

- [terraform docs](https://www.terraform.io/docs/cli/commands/init.html#general-options)

# Implementation Details
This should be a simple as adding a new property in the [bitops.schema.yaml for terraform](https://github.com/bitovi/bitops/blob/master/scripts/terraform/bitops.schema.yaml)

..and updating [the docs](https://github.com/bitovi/bitops/blob/master/docs/tool-configuration/configuration-terraform.md)

**Comment by PhillypHenning** [comment]
https://github.com/bitovi/bitops/pull/127
