### ISSUE TITLE
Terraform: support -backend-config parameter

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/bitops#120]
Terraform has a `-backend-config` parameter used like this:
```
-backend-config="KEY1=VALUE1" \
-backend-config="KEY2=VALUE2"
```

To support this, both of the following need to be implemented:
- https://github.com/bitovi/bitops/issues/118
- https://github.com/bitovi/bitops/issues/119

**Comment by PhillypHenning** [comment]
Issue resolved [https://github.com/bitovi/bitops/pull/121]
