### ISSUE TITLE
Terraform - don't run apply if destroy environment variable is set

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/bitops#130]
https://github.com/bitovi/bitops/blob/master/scripts/terraform/deploy.sh#L59-L75

if `TERRAFORM_DESTROY` env variable is set on bitops, but bitops.config.yaml says `command: apply`, it'll apply then destroy.  Not sure this is ideal

**Comment by LeoDiazL** [comment]
[To be resolved here](https://github.com/bitops-plugins/terraform/issues/14)
