### ISSUE TITLE
Helm - Copy Defaults - undefined env vars ERROR and NC

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/bitops#133]
https://github.com/bitovi/bitops/blob/master/scripts/helm/copy-defaults.sh

`ERROR` and `NC` seem to be undefined.  

Need to confirm they're undefined or, if not, comment where the values are coming from.

**Comment by PhillypHenning** [comment]
Current output from script; 
```
COPY_DEFAULT_CRDS set
 crds/ does not exist...COPY_DEFAULT_CHARTS set
 charts/ does not exist...COPY_DEFAULT_TEMPLATES set
  templates/ does not exist...COPY_DEFAULT_SCHEMA set
  schema/ does not exist...+ echo 'COPY_DEFAULT_TEMPLATES set'
  ```

**Comment by PhillypHenning** [comment]
Judging from the output the intention here was to use printf to create a line without a newline, than append the result (good or bad) to the end of the string. 

However the current formatting does the opposite.

**Comment by PhillypHenning** [comment]
Value of $ERROR = `\033[0;31m` 
Value of $NC = `\033[0m`

**Comment by PhillypHenning** [comment]
Moved to bitops-plugin/helm 

https://github.com/bitops-plugins/helm/issues/9
