### ISSUE TITLE
Cloud Provider bitops.config.yml

### ISSUE THREAD

**Issue by ConnorGraham** [bitovi/bitops#15]
Tools are configurable using decli schema. Cloud providers should have the same level of support so non-secret properties don't have to be configured via env vars

**Comment by mickmcgrath13** [comment]
This _should_ be handled with plugins:
https://github.com/bitovi/bitops/pull/55/files

**Comment by mickmcgrath13** [comment]
GCP started here: https://github.com/bitovi/bitops/pull/70

**Comment by mickmcgrath13** [comment]
GCP and Azure are documented here:
https://github.com/bitovi/bitops/tree/plugins/docs/cloud-configuration
