### ISSUE TITLE
Terraform/Ansible/etc Defaults

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/bitops#18]
Similar to how helm allows specification of `_default`, can we do the same with Terraform?

## Options
- Terraform multiple var files? (something to this effect: `terraform apply -auto-approve -f $DEFAULT_VARS_FILE -f $ENV_VARS_FILE`)
    - how does it handle the same keys/vars in multiple files?
- Terragrunt
- yaml-based stuff:
    - [ytt](https://get-ytt.io/)
    - [python terraform module](https://pypi.org/project/python-terraform/)

**Comment by PhillypHenning** [comment]
BitOps V2 version - https://github.com/bitovi/bitops/issues/177
