### ISSUE TITLE
Add AWS Temporary credentials support in BitOps

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#195]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.
](https://github.com/bitovi/bitops/pull/163)

# AC
- Add a new option to the aws plugin that will enable ENV_VAR file save for the AWS credentials

**Comment by shyamrayaprolu** [comment]
This ticket is created to make sure BitOps V2 supports both static and temporary aws credentials. 

Implement following logic:

```
mkdir -p /root/.aws
cat <<EOF > /root/.aws/credentials
[default]
aws_access_key_id = "${AWS_ACCESS_KEY_ID}"
aws_secret_access_key = "${AWS_SECRET_ACCESS_KEY}"
EOF

if [ -n "$AWS_SESSION_TOKEN" ]; then
  echo "aws_session_token = $AWS_SESSION_TOKEN" >> /root/.aws/credentials
fi


```
