### ISSUE TITLE
Plugin - CloudProvier - Google Cloud

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#219]
**Pulled from a depreciated file; [configuration-gcp.md](https://github.com/bitovi/bitops/blob/plugins-cleanup/docs/cloud-configuration/configuration-gcp.md)**
# GCP

Follow the steps in Google's documentation to create and download your GCP Authentication Key. 
See [Googles official documentation](https://cloud.google.com/docs/authentication/getting-started)

## Configuration

-------------------
### GOOGLE_AUTHENTICATION_KEY
* **BitOps Property:** 
* **Environment Variable:** `GOOGLE_AUTHENTICATION_KEY`
* **default:** `""`
* **required:** yes

**Comment by mickmcgrath13** [comment]
@PhillypHenning should this be re-opened?  We don't have a GCP plugin here: https://github.com/bitops-plugins

**Comment by PhillypHenning** [comment]
I closed this one in favor of the older one https://github.com/bitovi/bitops/issues/14

Shall i reverse that?

**Comment by mickmcgrath13** [comment]
nope. all good.  wasn't aware of the other one
