### ISSUE TITLE
Rename or remove master branch

### ISSUE THREAD

**Issue by ccapell** [bitovi/bitops#253]
There is both a `master` and `main` branch.  Currently, the default branch is main, however, this could cause confusion if you see master first.

Solution: Rename master to something like `old-master` or just remove the outdated branch.

**Comment by mickmcgrath13** [comment]
any objections to just removing it?  @phillipskevin @armab @ccapell ?

**Comment by armab** [comment]
+ 100

**Comment by armab** [comment]
The `master` branch was removed
