### ISSUE TITLE
Bitops Logo

### ISSUE THREAD

**Issue by ConnorGraham** [bitovi/bitops#27]
Bitops needs a logo ✨

**Comment by mickmcgrath13** [comment]
Cc @kylegifford @ryangwilson

**Comment by ryangwilson** [comment]
I have a graphic design contractor that I can reach out to. Do we have requirements set for this project?

**Comment by mickmcgrath13** [comment]
Not really. BitOps stands for "Bitovi Operations", so some consistency with Bitovi would be good.

'operations' in this case refers to system and infrastructure operations

**Comment by mickmcgrath13** [comment]
Done!!
