### ISSUE TITLE
Plugins configuration docs: format parameters as a table

### ISSUE THREAD

**Issue by armab** [bitovi/bitops#280]
Per @ccapell suggestion it would be much cleaner and user-friendly if we'd format the https://bitovi.github.io/bitops/configuration-base/ Configuration documentation for plugins, tools, and Cloud providers with a table instead of using a list that takes long scrolling and uses lots of space.

![image](https://user-images.githubusercontent.com/1533818/185231768-59d9a3c7-07bd-49a9-9c15-d64ca34a082c.png)

## TODO
- [ ] Update the subpages in the https://bitovi.github.io/bitops/configuration-base/
- [ ] Update every plugin README in the https://github.com/bitops-plugins

**Comment by mickmcgrath13** [comment]
💯 I agree with this
