### ISSUE TITLE
Allow inheriting from multiple environments

### ISSUE THREAD

**Issue by josh-bitovi** [bitovi/bitops#33]
There are times when it's useful to have multiple (configurable) levels of inheritance between environments. For example if you want a staging environment that inherits from default (as per usual) but also from prod, because it needs to be as close to prod as possible, with a few important tweaks.

Suggested config format:
```yaml
    # in bitops helm config
    alsoInheritFrom: # will need to document this
      # default controlled by other env vars
      - staging
```

Currently `default` is handled by a slew of vars that let you control _which parts_ of the default env are copied... but I'm not aware of these being used (i.e. I think we generally always inherit from default).

IMO it'd be better to:
- Always inherit from default
- Unless you specify the above config, in which case you can opt-in to default, or even put it in a different order

Another option would be to always use default (possibly retaining the vars to control if/how much of it is used), and just use the list for additional envs on top of default.

**Comment by PhillypHenning** [comment]
Beyond V2 - This is a major feature that will be introduced within the next few releases
