### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by LeoDiazL** [bitovi/bitops#332]
**Describe the bug**

Following the blog https://www.bitovi.com/blog/bitops-terraform-ansible

Adjusting the my-app/terraform/bitops.config.yaml contents following the 2.0 guide https://bitovi.github.io/bitops/migration/2.0-migration/#terraform

Will result in a `TypeError: 'NoneType' object is not subscriptable` error

**To Reproduce**

my-app/terraform/bitops.config.yaml contents 

```terraform:
    cli: 
    options:
        stack-action: apply
        fetch-kubeconfig: false
```
Will result in a `TypeError: 'NoneType' object is not subscriptable` error

Next config solves the issue

```terraform:
    cli: {}
    options:
        stack-action: apply
        fetch-kubeconfig: false
```

**Expected behavior**
BitOps should consider the lack of variable as if it was an empty arrayay. 

**Additional context**
This configs file where generated automatically by running the BitOps generator, then adjusted with the 2.0 guide.
Configuration file also includes a version option that's no longer used.
A warning message saying that the variable is not used could help clear unnecessary variables?

**Comment by mickmcgrath13** [comment]
I think this is resolved in 2 ways (`and` not `or`):
1. Docs updates (and blog update) to use `cli: {}`
2. Validate the schema: https://github.com/bitovi/bitops/issues/237

**Comment by armab** [comment]
```
TypeError: 'NoneType' object is not subscriptable
```
is not a good error.
This should be better handled in the code first for this specific case,
before diving into a more involved effort of https://github.com/bitovi/bitops/issues/237.
