### ISSUE TITLE
Helm default-sub-dir not being passed to plugin

### ISSUE THREAD

**Issue by LeoDiazL** [bitovi/bitops#333]
**Describe the bug**
helm plugin failing because of missing default-sub-dir path being passed.

**To Reproduce**
Make a deployment with helm charts

**Expected behavior**
Deploy helm chart without issues

**Additional context**

Running deployment with the following settings solves the issue

**Note the added default-sub-dir option** --> aws-auth should match the sub-dir of the helm folder.

`:~/ops-repo/some-env/helm/aws-auth$ cat bitops.config.yaml `
```
helm:
  cli:
    namespace: kube-system
    timeout: 200s
    debug: true
    atomic: false
    force: false
    dry-run: false
  options:
    release-name: aws-auth
    skip-deploy: false
    default-sub-dir: aws-auth
    k8s:
      fetch:
        kubeconfig: true
        cluster-name: prod-ekscluster
```

**Comment by mickmcgrath13** [comment]
I think it should be `default-sub-dir: helm/aws-auth`

also, I believe this will be resolved with:
https://github.com/bitops-plugins/helm/pull/8

**Comment by armab** [comment]
Fixed via https://github.com/bitops-plugins/helm/pull/8
