### ISSUE TITLE
Update docs site url and add CNAME file for new bitops.sh

### ISSUE THREAD

**Issue by PhillypHenning** [bitovi/bitops#342]
https://github.com/bitovi/bitops/pull/341

**Comment by PhillypHenning** [comment]
Suggested change applied based on https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages & https://stackoverflow.com/questions/54059217/how-to-fix-domain-does-not-resolve-to-the-github-pages-server-error-in-github

Change may take up to 24 hours to be applied. I'll have my eye on it

**Comment by PhillypHenning** [comment]
@mickmcgrath13 I don't have access to CloudFlare to update this. Could you put this on your short list for next week

**Comment by PhillypHenning** [comment]
<img width="919" alt="Screen Shot 2022-11-14 at 1 24 30 PM" src="https://user-images.githubusercontent.com/16713447/201737217-12f90b76-dc6d-4004-83b3-c3ee4ec95e40.png">

**Comment by PhillypHenning** [comment]
<img width="1110" alt="Screen Shot 2022-11-14 at 1 32 50 PM" src="https://user-images.githubusercontent.com/16713447/201738773-2cfb1310-7079-4ab0-8138-49853f27b90c.png">

I'm a bit hesitant to delete the `A` record to test a `CNAME`

Any concerns from your @mickmcgrath13

**Comment by mickmcgrath13** [comment]
I tried doing a cname through route53, and it doesn't seem possible..

**Comment by PhillypHenning** [comment]
What about using a proxy address such as;

`bitops.sh` - `A` - *Keep the same address list*
`github.bitops.sh` - `CNAME` - Alias to bitops.sh

Point the github pages as `github.bitops.sh`

**Comment by PhillypHenning** [comment]
<img width="786" alt="Screen Shot 2022-11-15 at 11 17 42 AM" src="https://user-images.githubusercontent.com/16713447/201971424-fe384099-02c1-4ec3-aced-6ceb9bacc9c8.png">

**Comment by PhillypHenning** [comment]
Closing in an hour @mickmcgrath13 @armab
