### ISSUE TITLE
BitOps should exit on tool failure

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/bitops#358]
**Describe the bug**
When a tool deployment fails, BitOps just keeps on going.

**To Reproduce**
1. Have an ops repo that deploys more than one tool
2. In the first tool, simulate a failure (use variables in a `variables.tf` file, for example)
3. Run BitOps against your environment
4. See error in first tool and BitOps continuing to subsequent tools

**Expected behavior**
When a tool deployment fails, BitOps exits.

**Screenshots**
![image](https://user-images.githubusercontent.com/1030325/202187817-348ecf78-5349-43f6-9238-2f00776fb2b4.png)
and then
![image](https://user-images.githubusercontent.com/1030325/202187866-715e5748-d1e9-4d2e-b7a2-a90d1f82f45f.png)

*System info*
* BitOps image tag used: 2.1.0

**Additional context**
[This if](https://github.com/bitovi/bitops/blob/main/scripts/plugins/deploy_plugins.py#L272) block should contain an exit command:
```
        if result.returncode == 0:
            logger.info(f"\n~#~#~#~DEPLOYING OPS REPO [{deployment}] SUCCESSFULLY COMPLETED~#~#~#~")
        else:
            logger.warning(f"\n~#~#~#~DEPLOYING OPS REPO [{deployment}] FAILED~#~#~#~")
            sys.exit(1)
```

**Comment by armab** [comment]
Same issue for Before hooks. Failure should stop the execution immediately: 

```
2022-11-17 18:28:42,715 root         WARNING ~#~#~#~BEFORE HOOK [create-tf-bucket.sh] FAILED~#~#~#~
2022-11-17 18:28:42,745 root         INFO 
                RUNNING DEPLOYMENT SCRIPT                            
                        LANGUAGE:       [bash]                            
                        SCRIPT PATH:    [/opt/bitops/scripts/plugins/terraform/deploy.sh]                            
                        STACK ACTION:   []
```

**Comment by armab** [comment]
Fixed in https://github.com/bitovi/bitops/pull/373
