### ISSUE TITLE
Use npx instead of yeoman

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/bitops#39]
[npx](https://www.npmjs.com/package/npx) is installed by default with NodeJS. It can do [one off invocation without local installation](https://www.npmjs.com/package/npx#one-off-invocation-without-local-installation)

Afaik, yeoman isn't really used that much by NodeJS devs anymore.  

I'd strongly consider switching to npx. It should allow you to change:

```
npm install -g yo
npm install -g @bitovi/generator-bitops
yo @bitovi/bitops
```

Into 

```
npx @bitovi/bitops
```

**Comment by mickmcgrath13** [comment]
would we use Yeoman under the hood, or would we need to rebuild the generator bits?

**Comment by mickmcgrath13** [comment]
Current Yeoman generator here:
https://github.com/bitovi/bitops-operations-repo-generator

**Comment by justinbmeyer** [comment]
You probably can use yeoman under the hood, or maybe there's something lighter than yeoman.  

Btw, for these "one-off" generators ... it's nice if you package all (or some) of your dependencies.  This way, the install happens much faster.

**Comment by justinbmeyer** [comment]
here's the code that builds the express generator: https://github.com/expressjs/generator/blob/master/bin/express-cli.js#L154

Looks like they just wrap EJS themselves.

**Comment by PhillypHenning** [comment]
Moving to V2 https://github.com/bitovi/bitops/issues/173
