### ISSUE TITLE
Bitops Plugins

### ISSUE THREAD

**Issue by mickmcgrath13** [bitovi/bitops#54]
## Description
Bitops needs to “understand” an operations repository (ops repo).  Currently, ops repos can contain `helm/` and `terraform/`, and this functionality is built into the tool itself.

To make Bitops more robust, it should be able to accept plugins that extend its core functionality.

For example, if my ops repo needs to describe an ansible deployment, there should be a way to build an ansible plugin and register it with bitops.

## Condiserations
One thing to consider is: should we rewrite bitops in a programming language (currently, it's bash)?

## Example

An example plugin might look something like this:

#### github.com/bitovi/bitops-plugin-ansible
`decli.schema.yaml`
```
# decli description file (converts yaml into an ansible command
```

`install.sh`
```
#!/bin/bash
apk add ansible
```

### Include in bitops
To include plugins in bitops, a container would need to be built.  To do this, one would create a **new** bitops repository and build a new container that uses bitops core as its base container.

#### github.com/some-org/bitops-custom
`Dockerfile`
```
FROM bitovi/bitops:latest
WORKDIR /opt/bitops
COPY ./plugins/ansible /opt/bitops/plugins/ansible
```

`bitops.config.yaml`
```
...
plugins:
    - name: ansible
       source: github.com/bitovi/bitops-plugin-ansible
```

### Additional thoughts for base images
Just a thought on making the underlying BitOps Docker Image to multilayer
Ex: Base Docker will have OS and other needed softwares, harden the image and tag it (with major/minor version). Idea of Golden AMI/image is what I am proposing
Application Docker which consists of bitops code base will point to the base docker. This way if there are any OS patches/softwares that need to be installed, we don't touch the bitops code base. And in the CI process we can pass the version of the base docker we want. This would eventually also solve problems like dealing with some older version of softwares.

**Comment by mickmcgrath13** [comment]
All of the following scripts should be migrated to plugins:
- ansible
- cloudformation
- helm
- kubectl
- terraform

Additionally, cloudproviders need to be pluggable, too.  we'll need to decide whether to have a separate `providers/` directory or if we want them to just be part of `plugins/`
- AWS
- GCP (todo: https://github.com/bitovi/bitops/pull/70)

Plugins should also be documented when the functionality is done

**Comment by mickmcgrath13** [comment]
Plugins should live in a new org like: github.com/bitops-plugins

**Comment by ian-bitovi** [comment]
@ConnorGraham Can you please create github.com/bitops-plugins? I don't have access. Thanks.

**Comment by ConnorGraham** [comment]
I don't have permissions either. @mickmcgrath13

**Comment by mickmcgrath13** [comment]
Create an org, right?

**Comment by ConnorGraham** [comment]
I might want to have a discussion around having a conversation around what to name the org to house bitops-core along with all the plugins, but assuming we can rename an org later - **Yes please create a `bitops-plugin` org**

**Comment by mickmcgrath13** [comment]
https://github.com/bitops-plugins

**Comment by mickmcgrath13** [comment]
so, thinking about this a bit more, I think i'd prefer if bitpos-core is not in the bitops-plugins org (regardless of naming).  The separation maintains the succinctness of a plugin library (i.e. all repos in this here org are plugins).  We can maintain permissions and scripts (like an index script) and such separately without additional logic (i.e. `if !bitops-core; then addToIndex()`)

thoughts?

**Comment by ConnorGraham** [comment]
I thought the purpose of having a `bitops*` github org was more for branding and discoverability purposes than any technical reasons.

I feel it will be easier to understand and find BitOps if everything is grouped in to a single org.

With your model, where would `bitops-core` reside?

**Comment by mickmcgrath13** [comment]
github.com/bitovi/bitops 🤷

**Comment by ian-bitovi** [comment]
So we have a successful test for BitOps Plugins with Terraform and Helm. I plan on launching a VM and test Ansible next.

**Comment by mickmcgrath13** [comment]
links, please

**Comment by armab** [comment]
It's helpful to be able to define custom plugins 👍 

One of the ideas for maybe the future plugin iteration would be having the plugins pre-built as docker images (one image per tool), so users won't need to build them and host on their own, but specify the tool + version which would be pulled for them and magically work in bitops.

I'll probably need to extract it into another Issue or discussion.

**Comment by mickmcgrath13** [comment]
@armab I'd like to see a dedicated discussion about the plugins-as-containers concept
