### ISSUE TITLE
Decli - Convert schema/config reconciliation from bash to python

### ISSUE THREAD

**Issue by ConnorGraham** [bitovi/bitops#59]
Our bash implementation is messy and error prone. Time to move to a proper programming language like python 
https://github.com/bitovi/bitops/tree/master/scripts/bitops-config

Another option is to build Decli - a standalone CLI tool:
https://github.com/bitovi/decli

## Description
Decli is a layer between a yaml file and a CLI tool wherein the keys in the yaml file are a declarative representation of a CLI command.  

This functionality would be the foundation for Bitops Plugins

## Example
For example, a `foo` executable has a signature that looks like this:
```
foo --optionA=”bar” --optionB
```
..and the yaml representation might look something like this:
```
name: foo
path: /path/to/foo
args:
    optionA: bar
    optionB: true
```
## Discussions
- [Slack](https://bitovi.slack.com/archives/CB18EJU00/p1585315862018400)

## Level of Effort
low-med

## Expertise Necessary
- Bash
- Yaml
- Any programming language

## Prior Art
- [Helmfile](https://github.com/roboll/helmfile) (declarative helm commands)

## Acceptance Criteria
- github.com/bitovi/decli exists
- decli can be executed from the command line (i.e. `decli -f /path/to/file.yaml`)
- decli can be used for any cli tool

**Comment by mickmcgrath13** [comment]
Related ticket (bitovi internal for now until we move it.. it has comments, so it's not a quick thing):
https://github.com/bitovi/devops/issues/73

**Comment by mickmcgrath13** [comment]
Additional bitops schema use case: set environment variables.
It _might_ make sense to also have Decli do environment variable stuff, too.
