### ISSUE TITLE
BitOps - SEO enhancment and optimization

### ISSUE THREAD

**Issue by dylan-bitovi** [bitovi/bitops#62]
When you search Google for BitOps, Bitovi is further down or even on the second page. It would be nice if we can bump ourselves up not only for BitOps searches but also rank highly with 'deployment' minded searches.

@ConnorGraham already did a number on Bitovi's devops page, but we should consider the same treatment for Bitops.

tl;dr - Tracking ticket for SEO initiatives. :)

**Comment by mickmcgrath13** [comment]
Here's the keyword/competitor analysis that was done for the main devops-consulting page (bitovi only):
https://docs.google.com/spreadsheets/d/1vTGq1asCPGoXpKe_lZ_6v8wRLE9YcK2hdGOdr8OGSCs/edit#gid=258901677

**Comment by dylan-bitovi** [comment]
## Terminology Direction:
- "devops deployment"
- "cloud deployment"
- "infrastructure as code" / "infrastructure as code (iac)"
- "agnostic deployment"
- "infrastructure management"
- "application infratstructure system"
- "operations repo"
- "manage your infrastructure as code"
- "infrastructure as code (iac) tools"
- "do you need infrastructure as code"

**Comment by dylan-bitovi** [comment]
## Goals for BitOps SEO 
- Define and describe measurable search terms & keywords that allow tracking of Bitops' progress
- Refine existing content
- Increase daily pull count for Bitops repo
- Encourage community developed plugins & engagment

## Terminology Direction:
Decide which keyword(s) we want to use as our main dowsing rod for tracking performance:
• "devops deployment"
• "cloud deployment"
• "infrastructure as code" / "infrastructure as code (iac)"
• "agnostic deployment"
• "infrastructure management"
• "application infratstructure system"
• "operations repo"
• "manage your infrastructure as code"
• "infrastructure as code (iac) tools"
• "do you need infrastructure as code"

## SEO Specific Witchcraft:
- Backlinking (guest blogs on medium/other public blog outlets)
- Pagespeed Score (https://developers.google.com/speed/pagespeed/insights/)
- TrustRank pages (About, Privacy Policy, Terms of Service, Contact)

## Specific Bitops page reccomendations:
- Update page header title (Bitops -> Bitovi - Bitops)
- Why BitOps ( Update to include some demonstration of value)
- Update meta page tag/description
- Update AWS cli image (transparent)
- No links to documentation / needs some fleshing out
- Bubble groupings like how Connor did for tools/Plugins on DevOps
- Graphic / gif / flowchart demonstrating value at a glance
- 'Open source' graphic contians a link but other two images do not
- Docs link is small / out of the way
- Graphics for 'configurable'/'event hooks'/'runs anywhere' headings
- Slack link to bitovi community but there’s no #bitops channel
- Development Guide page missing content
- Contributing > 'Open Issues' is an offsite link mixed with local links
- Lifecycle doc page should be split into headings that show in the TOC on left bar
- Built by Bitovi - change to Bitovi logo ?
- Lack of keywords: devops/plugin names/numbers/agnostic etc.

## Outside promotion:
* Clients using/used Bitops
  * Client bitops post mortem
    * Backlinked from client site?
   * StackStorm/StackStorm-ha

**Comment by mickmcgrath13** [comment]
@dylan-bitovi can we close this one since the efforts are all tracked in other tickets?
https://github.com/bitovi/bitops/projects/1?add_cards_query=is%3Aopen

**Comment by dylan-bitovi** [comment]
Done! 

There's also a milestone: https://github.com/bitovi/bitops/milestone/1
