### ISSUE TITLE
Add Ansible lifecycle docs regarding variable precedence

### ISSUE THREAD

**Issue by dylan-bitovi** [bitovi/bitops#69]
I was testing out my BitOps changes for verbose flagging as Ansible has a few ways to set verbosity at different points, and with verbosity now as an option for Ansible in BitOps I figured I should note my findings. 

tl;dr - there's three ways to set Ansible's verbosity flag in BitOps, and if multiple have been set, this is the order they take precedence in (1 being highest prio):
1. bitops.schema.yaml
2. export ANSIBLE_VERBOSITY at BitOps container runtime
3. set `verbosity=[0-4]` in `ansible.cfg` under `[defaults]` or a host grouping

I tried testing this with including the var in an `extra-vars` file, but Ansible does not seem to register the variable if included that way.

I mentioned this to Connor as I was thinking of where to put it, and he suggested somewhere in the Lifecycle section perhaps?

**Comment by mickmcgrath13** [comment]
@dylan-bitovi this is done, right?  Can you close if so?

**Comment by dylan-bitovi** [comment]
This can indeed be closed, the options are included in the documentation with a brief explanation.
