### ISSUE TITLE
[SEO] Define Bitops' Terminology keywords

### ISSUE THREAD

**Issue by dylan-bitovi** [bitovi/bitops#74]
Decide which keyword(s) we want to use as our main dowsing rod for tracking performance:
• "devops deployment"
• "cloud deployment"
• "infrastructure as code" / "infrastructure as code (iac)"
• "agnostic deployment"
• "infrastructure management"
• "application infratstructure system"
• "operations repo"
• "manage your infrastructure as code"
• "infrastructure as code (iac) tools"
• "do you need infrastructure as code"
* ?

**Comment by dylan-bitovi** [comment]
I've done more analysis and added it to the BitOps Keyword Analysis google sheet. None of the new terms or phrases I thought up compared to the first group (e.g. 'orchestration') fared any better.

The phrase: 'Infrastructure as code' has the highest volume (~6600), but also relatively high CPC (~$13.9). It has relatively low keyword competition/difficulty (6.36; below ~10 is considered 'easy') and the top 100 SERP pages are relevant to the space which Bitops will likely be operating in.

**Comment by dylan-bitovi** [comment]
I just discussed this briefly with Brian. 

Adding in 'orchestration tools' which ranked highly. Going to do another manual pass over some of the top keyword phrases using some of the insight from Brian.

**Comment by mickmcgrath13** [comment]
Great, thanks!

**Comment by dylan-bitovi** [comment]
These terms had been narrowed down to three main ones:

Keyword | Search Volume (Global) | CPC (Global)
-- | -- | --
devops tools | 22,200 | $3.28
infrastructure as code | 27,100 | $10.11
orchestration tools | 9,900 | $0.41

Both 'orchestration' and 'devops' are trending in volume, 'infrastructure as code' is more generic but defines one of the goals of BitOps
