### ISSUE TITLE
[Community] Create additional Bitops community resources

### ISSUE THREAD

**Issue by dylan-bitovi** [bitovi/bitops#77]
*  Slack channel
   * Create bot links for posting of comments when Bitops releases
   * Create bot links for linking tweets relating to Bitops

**Comment by mickmcgrath13** [comment]
I love this!

We have 2 options:
- Bitovi Community (we already have a devops channel, or we could create a separate BitOps one)
- Separate BitOps slack

I kinda like the latter, but I'm not sure what that looks like from a setup (or cost) perspective.

@dylan-bitovi (cc @kylegifford @moschel ) Thoughts?

**Comment by dylan-bitovi** [comment]
As it is the current docs page just links to the Bitovi Community - DevOps channel. If we're following the same sort of structure as the other Bitovi module specific channels (donejs/canjs/etc.) it makes sense to have an additional Bitops channel as opposed to an separate Slack entirely.

Linking it into the Bitops community at large also has the possibility of getting 'run-off' users into other Bitovi products; they might come for Bitops and end up using donejs, or vice-versa.

**Comment by kylegifford** [comment]
I would recommend going with a `bitops` channel in the Bitovi Community for now. If it for some reason necessitates its own Slack later (you need multiple channels related to Bitops dev vs support, for example), you could likely migrate to its own Workspace.

**Comment by dylan-bitovi** [comment]
This has been created:

https://bitovi-community.slack.com/archives/C01SX5L134G

Thanks @kylegifford !
